module.exports = {
  1: {
    en: "Receipt of payment from the buyer",
    au: "Receipt of payment from the buyer",
    it: "Ricevuta di pagamento da parte dell'acquirente",
    ch: "Zahlungseingang des Käufers",
    by: "Квитанция оплаты от покупателя",
    nl: "Ontvangst van betaling van de koper",
    cz: "Potvrzení o platbě od kupujícího",
    pt: "Recibo de pagamento do comprador",
    at: "Zahlungseingang des Käufers",
    es: "Recibo de pago del comprador",
    be: "Réception du paiement de l'acheteur",
    sk: "Potvrdenie o platbe od kupujúceho",
    de: "Zahlungseingang des Käufers",
    ro: "Chitanța plății de la cumpărător",
    ae: "استلام الدفع من المشتري",
  },
  2: {
    en: "RECEIVE MONE",
    au: "RECEIVE MONE",
    it: "RICEVERAI MONE",
    ch: "GELD ERHALTEN",
    pt: "RECEBER DINHEIRO",
    cz: "ZÍSKEJTE PENÍZE",
    nl: "ONTVANG GELD",
    by: "ПОЛУЧИТЬ ДЕНЬГИ",
    at: "GELD ERHALTEN",
    ro: "PRIMIȚI BANI",
    de: "GELD ERHALTEN",
    es: "RECIBIR MONEDA",
    be: "RECEVOIR DE L'ARGENT",
    ae: "احصل على المال",
    sk: "PRIJÍMAŤ PENIAZE",
  },
  3: {
    en: "Receiving payment is secure",
    au: "Receiving payment is secure",
    it: "Ricevere il pagamento è sicuro",
    ch: "Der Zahlungseingang ist sicher",
    pt: "Receber o pagamento é seguro",
    nl: "Het ontvangen van betaling is veilig",
    cz: "Příjem platby je bezpečný",
    de: "Der Zahlungseingang ist sicher",
    at: "Der Zahlungseingang ist sicher",
    be: "La réception du paiement est sécurisée",
    ro: "Primirea plății este sigură",
    es: "Recibir el pago es seguro",
    by: "Получение платежа безопасно",
    sk: "Príjem platby je bezpečný",
    ae: "استلام الدفع آمن",
  },
  4: {
    en: "By clicking the 'RECEIVE MONEY' button, you agree to the terms and conditions of the User Agreement by using the online service 'Secure Offer'",
    au: "By clicking the 'RECEIVE MONEY' button, you agree to the terms and conditions of the User Agreement by using the online service 'Secure Offer'",
    it: 'Facendo clic sul pulsante "RICEVI SOLDI", accetti i termini e le condizioni dell\'Accordo con l\'utente utilizzando il servizio online "Offerta sicura"',
    ch: "Indem Sie auf die Schaltfläche „GELD ERHALTEN“ klicken, stimmen Sie den Bedingungen der Benutzervereinbarung zu, indem Sie den Onlinedienst „Sicheres Angebot“ nutzen.",
    pt: "Ao clicar no botão 'RECEBER MONEY', você concorda com os termos e condições do Contrato do Usuário usando o serviço online 'Secure Offer'",
    nl: "Door op de knop 'GELD ONTVANGEN' te klikken, gaat u akkoord met de voorwaarden van de Gebruikersovereenkomst door gebruik te maken van de online service 'Veilig aanbod'",
    de: "Indem Sie auf die Schaltfläche „GELD ERHALTEN“ klicken, stimmen Sie den Bedingungen der Benutzervereinbarung zu, indem Sie den Onlinedienst „Sicheres Angebot“ nutzen.",
    cz: "Kliknutím na tlačítko „ZÍSKAT PENÍZE“ souhlasíte s podmínkami uživatelské smlouvy používáním online služby „Zabezpečená nabídka“",
    at: "Indem Sie auf die Schaltfläche „GELD ERHALTEN“ klicken, stimmen Sie den Bedingungen der Benutzervereinbarung zu, indem Sie den Onlinedienst „Sicheres Angebot“ nutzen.",
    ro: "Făcând clic pe butonul „PRIMIȚI BANI”, sunteți de acord cu termenii și condițiile Acordului de utilizare utilizând serviciul online „Ofertă sigură”",
    es: "Al hacer clic en el botón 'RECIBIR DINERO', usted acepta los términos y condiciones del Acuerdo de usuario mediante el uso del servicio en línea 'Oferta segura'",
    be: 'En cliquant sur le bouton "RECEVOIR DE L\'ARGENT", vous acceptez les termes et conditions du contrat d\'utilisation en utilisant le service en ligne "Offre sécurisée".',
    by: "Нажимая кнопку «ПОЛУЧИТЬ ДЕНЬГИ», вы соглашаетесь с условиями Пользовательского соглашения, используя онлайн-сервис «Безопасная оферта».",
    sk: "Kliknutím na tlačidlo „PRÍJEM PENIAZE“ súhlasíte s podmienkami zmluvy s používateľom používaním online služby „Bezpečná ponuka“",
    ae: 'بالنقر فوق الزر "تلقي الأموال" ، فإنك توافق على شروط وأحكام اتفاقية المستخدم باستخدام الخدمة عبر الإنترنت "العرض الآمن"',
  },
  5: {
    en: "Your item has been issued!",
    au: "Your item has been issued!",
    it: "Il tuo articolo è stato emesso!",
    ch: "Ihr Artikel wurde ausgestellt!",
    nl: "Uw item is uitgegeven!",
    de: "Ihr Artikel wurde ausgestellt!",
    cz: "Vaše položka byla vydána!",
    at: "Ihr Artikel wurde ausgestellt!",
    es: "¡Tu artículo ha sido emitido!",
    ro: "Articolul dvs. a fost emis!",
    be: "Votre article a été émis !",
    by: "Ваш товар выдан!",
    sk: "Vaša položka bola vydaná!",
    ae: "تم إصدار العنصر الخاص بك!",
    pt: "Seu item foi emitido!",
  },
  6: {
    en: "The buyer has already paid for the order.",
    au: "The buyer has already paid for the order.",
    it: "L'acquirente ha già pagato l'ordine.",
    ch: "Der Käufer hat die Bestellung bereits bezahlt.",
    de: "Der Käufer hat die Bestellung bereits bezahlt.",
    cz: "Kupující již objednávku zaplatil.",
    es: "El comprador ya ha pagado el pedido.",
    ro: "Cumpărătorul a plătit deja comanda.",
    at: "Der Käufer hat die Bestellung bereits bezahlt.",
    be: "L'acheteur a déjà payé la commande.",
    by: "Покупатель уже оплатил заказ.",
    sk: "Kupujúci už za objednávku zaplatil.",
    ae: "دفع المشتري ثمن الطلب بالفعل.",
    pt: "O comprador já pagou pelo pedido.",
    nl: "De koper heeft de bestelling al betaald.",
  },
  7: {
    en: "Delivery address",
    au: "Delivery address",
    it: "Indirizzo di consegna",
    de: "Lieferadresse",
    es: "Dirección de entrega",
    cz: "Doručovací adresa",
    ro: "Adresă de livrare",
    at: "Lieferadresse",
    by: "Адресс доставки",
    be: "Adresse de livraison",
    sk: "Adresa dodania",
    ch: "Lieferadresse",
    ae: "عنوان التسليم",
    pt: "Endereço de entrega",
    nl: "Bezorgadres",
  },
  8: {
    en: "Last name",
    au: "Last name",
    it: "Cognome",
    de: "Nachname",
    es: "Apellido",
    cz: "Příjmení",
    ro: "Numele de familie",
    at: "Nachname",
    be: "Nom de famille",
    by: "Фамилия",
    ch: "Nachname",
    sk: "Priezvisko",
    ae: "اللقب",
    pt: "Sobrenome",
    nl: "Achternaam",
  },
  9: {
    en: "First name",
    au: "First name",
    it: "Nome di battesimo",
    de: "Vorname",
    es: "Nombre de pila",
    cz: "Jméno",
    at: "Vorname",
    by: "Имя",
    ro: "Nume",
    be: "Prénom",
    ch: "Vorname",
    sk: "Krstné meno",
    ae: "الاسم الاول",
    pt: "Primeiro nome",
    nl: "Voornaam",
  },
  10: {
    en: "After receipt of funds, please send the goods the buyer according to the given data or hand over the goods to the courier who will call you back within within 12 hours",
    au: "After receipt of funds, please send the goods the buyer according to the given data or hand over the goods to the courier who will call you back within within 12 hours",
    it: "Dopo aver ricevuto i fondi, spedisci la merce all'acquirente secondo i dati forniti o consegna la merce al corriere che ti richiamerà entro 12 ore",
    de: "Nach Geldeingang senden Sie die Ware bitte gemäß den angegebenen Daten an den Käufer oder übergeben Sie die Ware dem Kurier, der Sie innerhalb von 12 Stunden zurückruft",
    cz: "Po obdržení finančních prostředků prosím zašlete zboží kupujícímu dle uvedených údajů nebo zboží předejte kurýrovi, který Vám do 12 hodin zavolá zpět",
    es: "Después de recibir los fondos, envíe los productos al comprador de acuerdo con los datos proporcionados o entregue los productos al servicio de mensajería, quien le devolverá la llamada dentro de las 12 horas.",
    at: "Nach Geldeingang senden Sie die Ware bitte gemäß den angegebenen Daten an den Käufer oder übergeben Sie die Ware dem Kurier, der Sie innerhalb von 12 Stunden zurückruft",
    by: "После поступления денежных средств, пожалуйста, отправьте товар покупателю по указанным данным или передайте товар курьеру, который перезвонит вам в течение 12 часов.",
    ro: "După primirea fondurilor, vă rugăm să trimiteți bunurile cumpărătorului conform datelor furnizate sau să predați mărfurile curierului care vă va suna înapoi în termen de 12 ore.",
    be: "Après réception des fonds, veuillez envoyer la marchandise à l'acheteur selon les données fournies ou remettre la marchandise au coursier qui vous rappellera dans les 12 heures",
    ch: "Nach Geldeingang senden Sie die Ware bitte gemäß den angegebenen Daten an den Käufer oder übergeben Sie die Ware dem Kurier, der Sie innerhalb von 12 Stunden zurückruft",
    sk: "Po obdržaní peňazí zašlite tovar kupujúcemu podľa uvedených údajov alebo odovzdajte tovar kuriérovi, ktorý Vám do 12 hodín zavolá späť",
    ae: "بعد استلام الأموال ، يرجى إرسال البضائع إلى المشتري وفقًا للبيانات المقدمة أو تسليم البضائع إلى شركة الشحن التي ستعاود الاتصال بك في غضون 12 ساعة",
    pt: "Após o recebimento dos fundos, envie as mercadorias ao comprador de acordo com os dados fornecidos ou entregue as mercadorias ao correio que ligará de volta dentro de 12 horas",
    nl: "Stuur na ontvangst van het geld de goederen naar de koper volgens de opgegeven gegevens of overhandig de goederen aan de koerier die u binnen 12 uur terugbelt",
  },
  11: {
    en: "After shipment of goods, please indicate to the buyer shipping number! The goods should be sent within within 3 days after receipt of funds",
    au: "After shipment of goods, please indicate to the buyer shipping number! The goods should be sent within within 3 days after receipt of funds",
    it: "Dopo la spedizione della merce, si prega di indicare all'acquirente il numero di spedizione! La merce deve essere spedita entro 3 giorni dal ricevimento dei fondi",
    de: "Nach Versand der Ware bitte dem Käufer die Versandnummer mitteilen! Die Ware sollte innerhalb von 3 Tagen nach Geldeingang versandt werden",
    cz: "Po odeslání zboží prosím sdělte kupujícímu přepravní číslo! Zboží by mělo být odesláno do 3 dnů po obdržení peněz",
    es: "¡Después del envío de las mercancías, indíquele al comprador el número de envío! Los productos deben enviarse dentro de los 3 días posteriores a la recepción de los fondos",
    at: "Nach Versand der Ware bitte dem Käufer die Versandnummer mitteilen! Die Ware sollte innerhalb von 3 Tagen nach Geldeingang versandt werden",
    ro: "După expedierea mărfurilor, vă rugăm să indicați cumpărătorului numărul de expediere! Bunurile trebuie trimise în termen de 3 zile de la primirea fondurilor",
    by: "После отгрузки товара, пожалуйста, сообщите покупателю номер доставки! Товар должен быть отправлен в течение 3-х дней после поступления денежных средств",
    be: "Après l'expédition des marchandises, veuillez indiquer à l'acheteur le numéro d'expédition ! Les marchandises doivent être envoyées dans les 3 jours suivant la réception des fonds",
    ch: "Nach Versand der Ware bitte dem Käufer die Versandnummer mitteilen! Die Ware sollte innerhalb von 3 Tagen nach Geldeingang versandt werden",
    sk: "Po odoslaní tovaru, prosím, uveďte kupujúcemu prepravné číslo! Tovar by mal byť odoslaný do 3 dní od prijatia peňazí",
    ae: "بعد شحن البضائع ، يرجى توضيح رقم الشحن للمشتري! يجب إرسال البضائع في غضون 3 أيام بعد استلام الأموال",
    pt: "Após o envio das mercadorias, indique ao comprador o número de envio! As mercadorias devem ser enviadas no prazo de 3 dias após o recebimento dos fundos",
    nl: "Na verzending van goederen, gelieve het verzendingsnummer van de koper door te geven! De goederen moeten binnen 3 dagen na ontvangst van het geld worden verzonden",
  },
  12: {
    en: "By clicking the 'RECEIVE MONEY' button, you agree to the terms and conditions of the User Agreement by using the online service 'Secure Offer'",
    au: "By clicking the 'RECEIVE MONEY' button, you agree to the terms and conditions of the User Agreement by using the online service 'Secure Offer'",
    it: 'Facendo clic sul pulsante "RICEVI SOLDI", accetti i termini e le condizioni dell\'Accordo con l\'utente utilizzando il servizio online "Offerta sicura"',
    de: "Indem Sie auf die Schaltfläche „GELD ERHALTEN“ klicken, stimmen Sie den Bedingungen der Benutzervereinbarung zu, indem Sie den Onlinedienst „Sicheres Angebot“ nutzen.",
    cz: "Kliknutím na tlačítko „ZÍSKAT PENÍZE“ souhlasíte s podmínkami uživatelské smlouvy používáním online služby „Zabezpečená nabídka“",
    es: "Al hacer clic en el botón 'RECIBIR DINERO', usted acepta los términos y condiciones del Acuerdo de usuario mediante el uso del servicio en línea 'Oferta segura'",
    at: "Indem Sie auf die Schaltfläche „GELD ERHALTEN“ klicken, stimmen Sie den Bedingungen der Benutzervereinbarung zu, indem Sie den Onlinedienst „Sicheres Angebot“ nutzen.",
    ro: "Făcând clic pe butonul „PRIMIȚI BANI”, sunteți de acord cu termenii și condițiile Acordului de utilizare utilizând serviciul online „Ofertă sigură”",
    by: "Нажимая кнопку «ПОЛУЧИТЬ ДЕНЬГИ», вы соглашаетесь с условиями Пользовательского соглашения, используя онлайн-сервис «Безопасная оферта».",
    be: 'En cliquant sur le bouton "RECEVOIR DE L\'ARGENT", vous acceptez les termes et conditions du contrat d\'utilisation en utilisant le service en ligne "Offre sécurisée".',
    ch: "Indem Sie auf die Schaltfläche „GELD ERHALTEN“ klicken, stimmen Sie den Bedingungen der Benutzervereinbarung zu, indem Sie den Onlinedienst „Sicheres Angebot“ nutzen.",
    sk: "Kliknutím na tlačidlo „PRÍJEM PENIAZE“ súhlasíte s podmienkami zmluvy s používateľom používaním online služby „Bezpečná ponuka“",
    ae: 'بالنقر فوق الزر "تلقي الأموال" ، فإنك توافق على شروط وأحكام اتفاقية المستخدم باستخدام الخدمة عبر الإنترنت "العرض الآمن"',
    pt: "Ao clicar no botão 'RECEBER MONEY', você concorda com os termos e condições do Contrato do Usuário usando o serviço online 'Secure Offer'",
    nl: "Door op de knop 'GELD ONTVANGEN' te klikken, gaat u akkoord met de voorwaarden van de Gebruikersovereenkomst door gebruik te maken van de online service 'Veilig aanbod'",
  },
  13: {
    en: "Delivery details",
    au: "Delivery details",
    it: "Dettagli di spedizione",
    de: "Lieferdetails",
    cz: "Detaily objednávky",
    es: "Detalles de la entrega",
    ro: "Detalii livrare",
    by: "Подробности доставки",
    be: "Détails de livraison",
    ch: "Lieferdetails",
    at: "Lieferdetails",
    sk: "Detaily doručenia",
    ae: "تفاصيل التسليم",
    pt: "Detalhes da Entrega",
    nl: "Verzendgegevens",
  },
  14: {
    en: "Overall",
    au: "Overall",
    it: "Complessivamente",
    de: "Gesamt",
    cz: "Celkově",
    ro: "Per total",
    by: "Общий",
    be: "Globalement",
    ch: "Gesamt",
    at: "Gesamt",
    sk: "Celkovo",
    es: "General",
    ae: "شاملة",
    pt: "No geral",
    nl: "Algemeen",
  },
};
